# Generated by Django 5.2.4 on 2025-07-29 05:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('warehouse', 'Entrepôt'), ('office', 'Bureau'), ('pickup_point', 'Point de retrait')], max_length=20, verbose_name="Type d'adresse")),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'établissement")),
                ('country', models.CharField(choices=[('US', 'États-Unis'), ('HT', 'Haïti'), ('CA', 'Canada'), ('FR', 'France')], max_length=2, verbose_name='Pays')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('address_line1', models.CharField(max_length=200, verbose_name='Adresse ligne 1')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Adresse ligne 2')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Code postal')),
                ('phone', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. Jusqu'à 15 chiffres autorisés.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('hours', models.TextField(help_text='Ex: Lun-Ven: 8h00-18h00, Sam: 9h00-15h00', verbose_name="Horaires d'ouverture")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_default_warehouse', models.BooleanField(default=False, help_text="Utilisé pour générer l'adresse personnalisée des utilisateurs", verbose_name='Entrepôt par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AddressService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('package_reception', 'Réception de colis'), ('consolidation', 'Consolidation'), ('sea_shipping', 'Expédition maritime'), ('air_shipping', 'Expédition aérienne'), ('express_shipping', 'Expédition express'), ('customer_service', 'Service client'), ('package_pickup', 'Retrait de colis'), ('payments', 'Paiements'), ('technical_support', 'Support technique')], max_length=50, verbose_name='Type de service')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('additional_info', models.CharField(blank=True, max_length=200, verbose_name='Informations supplémentaires')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='addresses.address', verbose_name='Adresse')),
            ],
            options={
                'verbose_name': "Service d'adresse",
                'verbose_name_plural': "Services d'adresse",
                'unique_together': {('address', 'service_type')},
            },
        ),
    ]
