# Generated by Django 5.2.4 on 2025-07-30 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=100, verbose_name='État/Province'),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse complète'),
        ),
    ]
