# Generated by Django 5.2.4 on 2025-07-29 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Belpanye', max_length=100, verbose_name="Nom de l'entreprise")),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'svg'])], verbose_name='Logo principal')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ico', 'png'])], verbose_name='Favicon')),
                ('primary_color', models.CharField(default='#3B82F6', max_length=7, verbose_name='Couleur principale')),
                ('secondary_color', models.CharField(default='#10B981', max_length=7, verbose_name='Couleur secondaire')),
                ('font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Lato', 'Lato'), ('Montserrat', 'Montserrat'), ('Poppins', 'Poppins')], default='Inter', max_length=50, verbose_name='Police de caractères')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter')),
                ('stripe_enabled', models.BooleanField(default=True, verbose_name='Activer Stripe')),
                ('paypal_enabled', models.BooleanField(default=False, verbose_name='Activer PayPal')),
                ('moncash_enabled', models.BooleanField(default=True, verbose_name='Activer MonCash')),
                ('stripe_publishable_key', models.CharField(blank=True, max_length=200, verbose_name='Clé publique Stripe')),
                ('paypal_client_id', models.CharField(blank=True, max_length=200, verbose_name='Client ID PayPal')),
                ('moncash_client_id', models.CharField(blank=True, max_length=200, verbose_name='Client ID MonCash')),
                ('usd_to_htg_rate', models.DecimalField(decimal_places=2, default=150.0, max_digits=10, verbose_name='Taux USD vers HTG')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Taux de TVA (%)')),
                ('handling_fee_per_package', models.DecimalField(decimal_places=2, default=2.0, max_digits=10, verbose_name='Frais de manutention par colis ($)')),
                ('email_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('sms_notifications_enabled', models.BooleanField(default=False, verbose_name='Notifications SMS')),
                ('whatsapp_notifications_enabled', models.BooleanField(default=True, verbose_name='Notifications WhatsApp')),
                ('smtp_host', models.CharField(blank=True, max_length=100, verbose_name='Serveur SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_username', models.CharField(blank=True, max_length=100, verbose_name='Utilisateur SMTP')),
                ('smtp_use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('notify_on_package_received', models.BooleanField(default=True, verbose_name='Notifier à la réception')),
                ('notify_on_shipment_created', models.BooleanField(default=True, verbose_name="Notifier à la création d'expédition")),
                ('notify_on_shipment_shipped', models.BooleanField(default=True, verbose_name="Notifier à l'expédition")),
                ('notify_on_shipment_delivered', models.BooleanField(default=True, verbose_name='Notifier à la livraison')),
                ('consolidation_enabled', models.BooleanField(default=True, verbose_name='Activer la consolidation')),
                ('free_storage_days', models.IntegerField(default=30, verbose_name='Jours de stockage gratuit')),
                ('public_tracking_enabled', models.BooleanField(default=True, verbose_name='Tracking public')),
                ('air_shipping_enabled', models.BooleanField(default=True, verbose_name='Transport aérien')),
                ('sea_shipping_enabled', models.BooleanField(default=True, verbose_name='Transport maritime')),
                ('express_shipping_enabled', models.BooleanField(default=False, verbose_name='Livraison express')),
                ('air_shipping_rate_per_kg', models.DecimalField(decimal_places=2, default=15.0, max_digits=10, verbose_name='Prix transport aérien ($/kg)')),
                ('sea_shipping_rate_per_kg', models.DecimalField(decimal_places=2, default=8.0, max_digits=10, verbose_name='Prix transport maritime ($/kg)')),
                ('express_shipping_rate_per_kg', models.DecimalField(decimal_places=2, default=25.0, max_digits=10, verbose_name='Prix livraison express ($/kg)')),
                ('allowed_delivery_countries', models.TextField(default='Haiti', help_text='Un pays par ligne', verbose_name='Pays de livraison autorisés')),
                ('available_languages', models.CharField(default='fr,en', help_text='Codes séparés par des virgules (ex: fr,en,ht)', max_length=50, verbose_name='Langues disponibles')),
                ('welcome_message_fr', models.TextField(default='Bienvenue sur Belpanye - Votre service de réexpédition vers Haïti', verbose_name="Message d'accueil (Français)")),
                ('welcome_message_en', models.TextField(default='Welcome to Belpanye - Your package forwarding service to Haiti', verbose_name="Message d'accueil (Anglais)")),
                ('privacy_policy', models.TextField(blank=True, verbose_name='Politique de confidentialité')),
                ('terms_of_service', models.TextField(blank=True, verbose_name="Conditions d'utilisation")),
                ('email_verification_required', models.BooleanField(default=True, verbose_name='Vérification email obligatoire')),
                ('manual_account_approval', models.BooleanField(default=False, verbose_name='Validation manuelle des comptes')),
                ('max_packages_per_user', models.IntegerField(default=10, verbose_name='Nombre max de colis par utilisateur')),
                ('max_package_weight_kg', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='Poids max par colis (kg)')),
                ('two_factor_auth_enabled', models.BooleanField(default=False, verbose_name='Authentification à 2 facteurs')),
                ('blocked_countries', models.TextField(blank=True, help_text='Un pays par ligne', verbose_name='Pays bloqués')),
                ('default_report_period', models.CharField(choices=[('week', 'Semaine'), ('month', 'Mois'), ('quarter', 'Trimestre'), ('year', 'Année')], default='month', max_length=20, verbose_name='Période par défaut des rapports')),
                ('auto_export_reports', models.BooleanField(default=False, verbose_name='Export automatique des rapports')),
                ('client_report_access', models.BooleanField(default=True, verbose_name='Accès client aux rapports')),
                ('is_active', models.BooleanField(default=True, verbose_name='Configuration active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Configuration de l'application",
                'verbose_name_plural': "Configurations de l'application",
            },
        ),
        migrations.CreateModel(
            name='MaintenanceMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Mode maintenance actif')),
                ('message', models.TextField(default='Site en maintenance. Nous reviendrons bientôt!', verbose_name='Message de maintenance')),
                ('estimated_end_time', models.DateTimeField(blank=True, null=True, verbose_name='Fin estimée')),
                ('allowed_ips', models.TextField(blank=True, help_text='Une IP par ligne', verbose_name='IPs autorisées')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mode maintenance',
                'verbose_name_plural': 'Modes maintenance',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('package_received', 'Colis reçu'), ('shipment_created', 'Expédition créée'), ('shipment_shipped', 'Expédition envoyée'), ('shipment_delivered', 'Expédition livrée'), ('payment_received', 'Paiement reçu'), ('account_created', 'Compte créé')], max_length=50, unique=True)),
                ('email_subject', models.CharField(max_length=200, verbose_name='Sujet email')),
                ('email_body', models.TextField(verbose_name='Corps email')),
                ('sms_body', models.TextField(max_length=1600, verbose_name='Message SMS/WhatsApp')),
                ('available_variables', models.TextField(editable=False, help_text='Variables utilisables: {user_name}, {package_number}, {tracking_number}, etc.', verbose_name='Variables disponibles')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template de notification',
                'verbose_name_plural': 'Templates de notifications',
            },
        ),
    ]
