# Generated by Django 5.2.4 on 2025-07-29 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appconfiguration',
            name='secondary_color',
        ),
    ]
