# Generated by Django 5.2.4 on 2025-07-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_secondary_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfiguration',
            name='air_shipping_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix transport aérien ($/kg)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='express_shipping_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix livraison express ($/kg)'),
        ),
        migrations.AlterField(
            model_name='appconfiguration',
            name='sea_shipping_rate_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix transport maritime ($/kg)'),
        ),
    ]
