# Generated by Django 5.2.4 on 2025-07-28 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('sender', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, help_text='Poids en kg', max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, help_text='Longueur en cm', max_digits=6)),
                ('width', models.DecimalField(decimal_places=2, help_text='Largeur en cm', max_digits=6)),
                ('height', models.DecimalField(decimal_places=2, help_text='Hauteur en cm', max_digits=6)),
                ('value', models.DecimalField(decimal_places=2, help_text='Valeur déclarée en USD', max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('status', models.CharField(choices=[('received', 'Reçu'), ('waiting', 'En attente'), ('ready', 'Prêt à expédier'), ('shipped', 'Expédié'), ('delivered', 'Livré')], default='received', max_length=20)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageConsolidation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consolidation_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('total_weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('packages', models.ManyToManyField(related_name='consolidations', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
