# Generated by Django 5.2.4 on 2025-07-29 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='agent_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_registered', to=settings.AUTH_USER_MODEL, verbose_name='Agent de réception'),
        ),
        migrations.AddField(
            model_name='package',
            name='announced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='destination',
            field=models.CharField(blank=True, max_length=200, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='package',
            name='fragility',
            field=models.CharField(choices=[('normal', 'Normal'), ('fragile', 'Fragile'), ('very_fragile', 'Très fragile')], default='normal', max_length=20, verbose_name='Fragilité'),
        ),
        migrations.AddField(
            model_name='package',
            name='shipping_mode',
            field=models.CharField(choices=[('normal', 'Normal'), ('express', 'Express')], default='normal', max_length=20, verbose_name="Mode d'expédition"),
        ),
        migrations.AlterField(
            model_name='package',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('announced', 'Annoncé par le client'), ('received', "Reçu à l'entrepôt"), ('waiting', 'En attente'), ('ready', 'Prêt à expédier'), ('shipped', 'Expédié'), ('delivered', 'Livré')], default='announced', max_length=20),
        ),
        migrations.CreateModel(
            name='PackageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100, verbose_name='Nom du destinataire')),
                ('recipient_id', models.CharField(max_length=50, verbose_name="Pièce d'identité du destinataire")),
                ('signature', models.TextField(blank=True, verbose_name='Signature (base64)')),
                ('delivery_photo', models.ImageField(blank=True, null=True, upload_to='deliveries/', verbose_name='Photo de livraison')),
                ('delivered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notes de livraison')),
                ('agent_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries_made', to=settings.AUTH_USER_MODEL, verbose_name='Agent de livraison')),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='packages.package')),
            ],
            options={
                'verbose_name': 'Livraison',
                'verbose_name_plural': 'Livraisons',
            },
        ),
        migrations.CreateModel(
            name='PackagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('method', models.CharField(choices=[('moncash', 'MonCash'), ('bank_transfer', 'Virement bancaire'), ('spih', 'SPIH'), ('credit_card', 'Carte de crédit'), ('cash', 'Espèces')], max_length=20, verbose_name='Méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transaction')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='packages.package')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
