# Generated by Django 5.2.4 on 2025-07-30 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_package_agent_in_package_announced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='fragility',
            field=models.CharField(choices=[('normal', 'Normal'), ('fragile', 'Fragile'), ('very_fragile', 'Very fragile')], default='normal', max_length=20, verbose_name='Fragilité'),
        ),
        migrations.AlterField(
            model_name='package',
            name='shipping_mode',
            field=models.CharField(choices=[('plane', 'Plane'), ('boat', 'Boat'), ('express', 'Express')], default='normal', max_length=20, verbose_name="Mode d'expédition"),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('announced', 'Announced'), ('received', 'Reçeived'), ('inTransit', 'In-Transit'), ('available', 'Available'), ('delivered', 'Livré')], default='announced', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='weight',
            field=models.DecimalField(decimal_places=2, help_text='Poids en lbs', max_digits=6),
        ),
    ]
