# Generated by Django 5.2.4 on 2025-07-28 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('air', 'Aérien'), ('sea', 'Maritime')], max_length=10)),
                ('min_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('delivery_days', models.IntegerField(help_text='Nombre de jours de livraison estimé')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['shipping_type', 'min_weight'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_number', models.CharField(blank=True, max_length=100, unique=True)),
                ('shipping_type', models.CharField(choices=[('air', 'Aérien'), ('sea', 'Maritime')], max_length=10)),
                ('total_weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente de paiement'), ('paid', 'Payé'), ('processing', 'En traitement'), ('shipped', 'Expédié'), ('in_transit', 'En transit'), ('delivered', 'Livré'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('tracking_number_haiti', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('consolidation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='packages.packageconsolidation')),
                ('packages', models.ManyToManyField(blank=True, related_name='shipments', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('stripe', 'Carte de crédit'), ('paypal', 'PayPal'), ('moncash', 'MonCash'), ('bank_transfer', 'Virement bancaire')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('payment_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='shipments.shipment')),
            ],
        ),
    ]
