# Generated by Django 5.2.4 on 2025-07-29 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('agent_in', 'Agent In'), ('agent_out', 'Agent Out'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='Rôle utilisateur'),
        ),
        migrations.CreateModel(
            name='PackageVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delegate_name', models.CharField(max_length=100, verbose_name='Nom du délégué')),
                ('delegate_phone', models.CharField(max_length=20, verbose_name='Téléphone du délégué')),
                ('delegate_id_number', models.CharField(max_length=50, verbose_name="Numéro de pièce d'identité")),
                ('package_tracking', models.CharField(blank=True, max_length=50, verbose_name='Numéro de suivi du colis')),
                ('is_active', models.BooleanField(default=True, verbose_name='Visa actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes additionnelles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas_given', to=settings.AUTH_USER_MODEL, verbose_name='Client propriétaire')),
            ],
            options={
                'verbose_name': 'Visa de colis',
                'verbose_name_plural': 'Visas de colis',
            },
        ),
    ]
