# Generated by Django 5.2.4 on 2025-07-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_role_packagevisa'),
    ]

    operations = [
    ]
